### PR TITLE
Dev parallel

### PR DESCRIPTION
**Pull request by gtrabes**
Parallel version added
-ParallelRootCoordinator added
-parallelPropagate added on Port to guarantee routing messages in parallel

### CODE REVIEW

**Review by romancardenas — APPROVED** [review]

**Review by romancardenas — CHANGES_REQUESTED** [review]
It seems that running OpenMP on MacOS is not that straightforward... Could you please isolate the parallel examples and modify CMakeLists.txt so the compilation of these examples only occurs if OpenMP is found?

**Comment by romancardenas** [comment]
I modified the code so now:
- the compilation of parallel versions is OPTIONAL (only if CMake is able to find OpenMP)
- the parallel root coordinator is CROSS-PLATFORM (only tested on MacOS and Ubuntu, we need to check Windows too)
- The EFP example now accepts a `flatten` parameter so, with just one example, we can choose either to flatten the model or not

FOR FUTURE:
The indentation is a mess (my bad). I think we should enforce using 4 spaces per indentation level. I modified a few files, but will do it for the entire project.

@gtrabes please, review my push and check that my changes make sense

**Comment by gtrabes** [comment]
Looks good to me, let's merge it!

**Comment by romancardenas** [comment]
First version for parallel simulation.

**Pull request merged**
